# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
        config.vm.define "gw02" do |xenial|
                xenial.vm.box = "centos/7"
		xenial.vm.hostname = "gw02.site02.frozza.com"
                xenial.vm.network "private_network", ip:"192.168.1.22"
                xenial.vm.network "private_network", ip:"172.16.0.11"
		xenial.vm.network "private_network", ip:"172.16.0.22"
		xenial.vm.network :forwarded_port, guest: 22, host: 22202
                xenial.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
			v.customize ["modifyvm", :id, "--groups", "/LPIC_202/site02"]
			v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
			v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
			v.customize ["modifyvm", :id, "--nicpromisc4", "allow-all"]
			v.name = "gw02"
                        v.memory = 1024
                        v.cpus = 2
                 end
        end
#	config.vm.provision :shell, :inline => "echo '192.168.1.111 router1.frozza.com router1' >> /etc/hosts"

        config.vm.define "mail02" do |xenial|
                xenial.vm.box = "centos/7"
		xenial.vm.hostname = "mail02.site02.frozza.com"
		xenial.vm.network "private_network", ip:"172.16.0.5"
		xenial.vm.network :forwarded_port, guest: 22, host: 22205
                xenial.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
			v.customize ["modifyvm", :id, "--groups", "/LPIC_202/site02"]
			v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
			v.name = "mail02"
                        v.memory = 768
                        v.cpus = 2
                 end
        end

        config.vm.define "auth02" do |xenial|
                xenial.vm.box = "ubuntu/xenial64"
		xenial.vm.hostname = "auth02.site02.frozza.com"
		xenial.vm.network "private_network", ip:"172.16.0.4"
		xenial.vm.network :forwarded_port, guest: 22, host: 22204
                xenial.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
			v.customize ["modifyvm", :id, "--groups", "/LPIC_202/site02"]
			v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
			v.name = "auth02"
                        v.memory = 768
                        v.cpus = 2
                 end
        end

        config.vm.define "user02" do |xenial|
                xenial.vm.box = "ubuntu/xenial64"
		xenial.vm.hostname = "user02.site02.frozza.com"
		xenial.vm.network "private_network", ip:"172.16.0.10"
		xenial.vm.network :forwarded_port, guest: 22, host: 22210
                xenial.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
			v.customize ["modifyvm", :id, "--groups", "/LPIC_202/site02"]
			v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
			v.name = "user02"
                        v.memory = 768
                        v.cpus = 2
                 end
        end
end
